classrooms/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('classrooms.views',
	(r'^test/', 'test'),
)

urlpatterns += patterns('classrooms.ajax',
    (r'^createGroup/$', 'createGroup'),
    (r'^deleteSession/$', 'deleteSession'),
    (r'^changeGroupName/$', 'changeGroupName'),
    (r'^toggleLockGroup/$', 'toggleLockGroup'),
    (r'^joinGroup/$', 'joinGroup'),
    (r'^postMessage/$', 'postMessage'),
    (r'^deleteMessage/$', 'deleteMessage'),
    (r'^editProfile/$', 'editProfile'),
    (r'^getOldMessages/$', 'getOldMessages'),
    (r'^getNewMessages/$', 'getNewMessages'),
    (r'^addSession/$', 'addSession'),
    (r'^editSession/$', 'editSession'),
    (r'^allSessionsPrint/(?P<sessionID>\d+)/$', 'allSessionsPrint'),
    (r'^allSessionsPrint/$', 'allSessionsPrint'),
    (r'^mySchedulePrint/(?P<userID>\d+)/$', 'mySchedulePrint'),
    (r'^mySchedulePrint/$', 'mySchedulePrint'),
    (r'^unscheduled/$', 'unscheduled'),
    (r'^forceAndToggleLock/$', 'forceAndToggleLock'),
)

google_login/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    (r'^logout/$', 'django.contrib.auth.views.logout',{'next_page': '/google/login'}),
)

urlpatterns += patterns('google_login.views',
    (r'^login/$', 'index'),
    (r'^auth/$', 'auth'),
    (r'^oauth2callback/$', 'auth_return'),
    (r'^success/$', 'success'),
    (r'^error/$', 'error'),
    (r'^forgot/(?P<forgotID>\d+)/$', 'forgotPassword'),
    (r'^passwordReset/$', 'passwordReset'),

#------------------ajax calls -------------------------------------
    url(r'^ajaxAuth/$', 'ajaxAuth', name='ajaxAuth'),
    url(r'^checkUsername/$', 'checkUsername', name='checkUsername'),
    url(r'^submitRegistration/$', 'submitRegistration', name='submitRegistration'),
    url(r'^doesEmailExist/$', 'doesEmailExist', name='doesEmailExist'),
    url(r'^submitPasswordForgot/$', 'submitPasswordForgot', name='submitPasswordForgot'),
    
)

workshop_project/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^google/', include('google_login.urls')),
    url(r'^class/', include('classrooms.urls')),
    #url(r'^profile/', include('userInfo_profile.urls')),
    
    
    (r'^media/(?P<path>.*)$', 'django.views.static.serve',
                 {'document_root': settings.MEDIA_ROOT}),
    
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#local views file
urlpatterns += patterns('workshop_project.views',
                        url(r'^$', 'index'),
                        url(r'^dashboard/$', 'dashboard', name="dashboard"),
                        url(r'^classView/(?P<classID>\d+)/$', 'classView', name='classView'),
                        url(r'^studentView/(?P<studentID>\d+)/$', 'studentView', name='studentView'),
                        url(r'^classView/$', 'classView', name='classView'),
                        url(r'^studentView/$', 'studentView', name='studentView'),
                        url(r'^conferenceView/$', 'conferenceView', name='conferenceView'),
)

classrooms/models.py
import datetime

from django.contrib import admin
from django.contrib.auth.models import User
from django.db import models


class Message(models.Model):
    text = models.TextField(max_length=150)
    timeDate = models.DateTimeField(auto_now=True)
    
    
    def __unicode__(self):
      return u'%s' % (self.text)
    
    
    class Meta:
        ordering = ['-timeDate']
    

class HashTag(models.Model):
    tag = models.CharField(max_length=45)
    timeDate = models.DateTimeField(auto_now=True)
    messages = models.ManyToManyField(Message, blank=True, null=True)
    classroomID = models.IntegerField()
    
    
    def __unicode__(self):
      return u'%s' % (self.tag)

    
class Classroom(models.Model):
    name = models.CharField(max_length=45)
    code = models.CharField(max_length=10)
    messages = models.ManyToManyField(Message, blank=True, null=True)
    allowJoin = models.BooleanField(default=True)
    classOwnerID = models.IntegerField()
    allUserClass = models.BooleanField(default=False)
    description = models.CharField(max_length=210, blank=True, null=True)
    classDate = models.DateField(auto_now=False, blank=True, null=True)
    startTime = models.TimeField(blank=True, null=True)
    endTime = models.TimeField(blank=True, null=True)
    location = models.CharField(max_length=45, blank=True, null=True)
    active = models.BooleanField(default=True)
    classLimit = models.IntegerField(default=30)
    classSize = models.IntegerField(default=0)
    classFull = models.BooleanField(default=False)
    
    


    def __unicode__(self):
      return u'%s on: %s from: %s to %s in %s' % (self.name, self.classDate, self.startTime, self.endTime, self.location)
    
    
    class Meta:
        ordering = ['classDate', 'startTime']
        verbose_name = 'Session'
        verbose_name_plural = 'Sessions'

class ClassUser(models.Model):
    user = models.ForeignKey(User)
    teacher = models.BooleanField(default=False)
    readOnly = models.BooleanField(default=False)
    messages = models.ManyToManyField(Message, blank=True, null=True)
    classrooms = models.ManyToManyField(Classroom, blank=True, null=True)
    avatarBackColor = models.CharField(max_length=45, blank=True, null=True)
    avatarTextColor = models.CharField(max_length=45, blank=True, null=True)


    def __unicode__(self):
      return u'%s, %s' % (self.user.last_name, self.user.first_name)
    
    
    class Meta:
        ordering = ['user__last_name',]
        verbose_name = 'Session Attendee'
        verbose_name_plural = 'Session Attendees'
    
    
    def user_full_name(self):
        return u'%s, %s' % (self.user.last_name, self.user.first_name)

    user_full_name.allow_tags = True
    user_full_name.admin_order_field = 'user'
    
    
    
    
    
    
    
    
    
    
    
    
    

classrooms/views.py
import os
ROOT_PATH = os.path.dirname(__file__)

from django.shortcuts import render_to_response, redirect, get_object_or_404
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from classrooms.models import *
from classrooms import settings



def test(request):
	getString = test_function()
	return HttpResponse(getString)
	
	
@login_required
def dashboard(request, classID=False):
    if ClassUser.objects.filter(user=request.user):
        classUser = ClassUser.objects.get(user=request.user)
    else:
        return redirect('/class/test/')
    
    #Get total number of messages made by user.
    if classUser.messages.all():
        messageCount = classUser.messages.all().count()
    else:
        messageCount = 0;
        
    #Get all users classes
    if classUser.classrooms.all():
        allClasses = classUser.classrooms.all()
    else:
        allClasses = False
        
    
    #Get Trending for the class
    if classID:
        if HashTag.objects.filter(classroomID=classID):
            trendings = HashTag.objects.filter(classroomID=classID).order_by('-timeDate')[:20]
        else:
            trendings = False
    elif allClasses:
        if HashTag.objects.filter(classroomID=allClasses[0].id):
            trendings = HashTag.objects.filter(classroomID=allClasses[0].id).order_by('-timeDate')[:20]
        else:
            trendings = False
    else:
        trendings = False
        
    
    #Get Current Class
    if classID:
        if Classroom.objects.filter(id=classID):
            currentClass = Classroom.objects.get(id=classID)
        else:
            currentClass = False
    elif allClasses:
        currentClass = allClasses[0]
    else:
        currentClass = False
        
    
    #Get Messages
    if currentClass:
        if currentClass.messages.all():
            messages = currentClass.messages.all().order_by('-timeDate')[0:20]
        else:
            messages = False
    else:
        messages = False
    
    return render_to_response('index.html', {
            'user':request.user,
            'classUser':classUser,
            'messageCount':messageCount,
            'allClasses':allClasses,
            'trendings':trendings,
            'currentClass':currentClass,
            'messages':messages,
        })







#---------------------------------- Special Functions ----------------------------------------


import string
from time import time
from itertools import chain
from random import seed, choice, sample


def generateCode(length=5, digits=3, upper=0, lower=2):
    seed(time())

    lowercase = string.lowercase.translate(None, "o")
    uppercase = string.uppercase.translate(None, "O")
    letters = "{0:s}{1:s}".format(lowercase, uppercase)

    password = list(
        chain(
            (choice(uppercase) for _ in range(upper)),
            (choice(lowercase) for _ in range(lower)),
            (choice(string.digits) for _ in range(digits)),
            (choice(letters) for _ in range((length - digits - upper - lower)))
        )
    )

    return "".join(sample(password, len(password)))

classrooms/templates/classrooms/allSessions.html
<!DOCTYPE html>

<html>
<head>
    <title>All Sessions</title>
    <style>
        @media print {
            .break {page-break-after: always;}
        }
    </style>
</head>

<body>

    {% if oneSession %}
    <div style="float: left; width: 100%; padding: 20px;">
        <div style="float: left;margin:5px;width: 45%;">
            <h1>Session:  {{ oneSession.name|title }}</h1>
            <h5>Description: {{oneSession.description}}</h5>
        </div>
        <div style="float: right;width: 45%;">
            <div><h3>date:  {{ oneSession.classDate|date }}</h3></div>
            <div><h3>time:  {{ oneSession.startTime|time }} to {{ oneSession.endTime|time }}</h3></div>
            <div><h3>location: {{ oneSession.location }}</h3></div>
        </div>
    </div>
    <div style="float: left; width: 100%;padding: 20px 20px 20px 40px;border-top: 1px solid #000;border-bottom: 1px solid #000">
        <div>Class Roster:</div><br>
       {% if oneSession.classuser_set.all %}
           {% if oneSession.classFull %}
                <br>
        <div><h1 style="color:red;">CLASS IS FULL WITH {{ oneSession.classSize }}.</h1></div>
            <br>
           {% endif %}
           {% for userInfo in oneSession.classuser_set.all %}
        <div>{{forloop.counter}}.  {{ userInfo.user.first_name|capfirst }} {{ userInfo.user.last_name|capfirst }}</div>
           {% endfor %}
       {% endif %}
    </div>
    <p class="break">page {{ forloop.counter }}</p>
        
    {% elif sessions %}
        {% for session in sessions %}
    <div style="float: left; width: 100%; padding: 20px;">
        <div style="float: left;margin:5px;width: 45%;">
            <h1>Session:  {{ session.name|title }}</h1>
            <h5>Description: {{session.description}}</h5>
        </div>
        <div style="float: right;width: 45%;">
            <div><h3>date:  {{ session.classDate|date }}</h3></div>
            <div><h3>time:  {{ session.startTime|time }} to {{ session.endTime|time }}</h3></div>
            <div><h3>location: {{ session.location }}</h3></div>
        </div>
    </div>
    <div style="float: left; width: 100%;padding: 20px 20px 20px 40px;border-top: 1px solid #000;border-bottom: 1px solid #000">
        <div>Class Roster:</div><br>
       {% if session.classuser_set.all %}
           {% if session.classFull %}
                <br>
        <div><h1 style="color:red;">CLASS IS FULL WITH {{ session.classSize }}.</h1></div>
            <br>
           {% endif %}
           {% for userInfo in session.classuser_set.all %}
        <div>{{forloop.counter}}.  {{ userInfo.user.first_name|capfirst }} {{ userInfo.user.last_name|capfirst }}</div>
           {% endfor %}
       {% endif %}
    </div>
    <p class="break">page {{ forloop.counter }}</p>
        {% endfor %}
    {% else %}
        Sorry, there are no sessions.<br>
    {% endif %}




</body>
</html>

classrooms/templates/classrooms/mySchedulePrint.html
<style>
    table, th, td {
   border: 1px solid black;
    }
    th, td {padding: 10px;}
</style>

{% load my_tags %}
{% if mySessions %}
<div style="float: left; width: 100%; padding: 20px;">
    <div style="float: left;margin:5px;width: 45%;">
        <h1>{{ userInfo.user.first_name|capfirst }} {{ userInfo.user.last_name|capfirst|possession }} Schedule</h1>
    </div>
</div>
<div style="float: left; width: 100%;padding: 20px 20px 20px 40px;border-top: 1px solid #000;border-bottom: 1px solid #000">
   
              <table>
                <thead>
                  <tr>
                    <th>Date</th>
                    <th>Name</th>
                    <th>Start Time</th>
                    <th>End Time</th>
                    <th>Location</th>
                  </tr>
                </thead>
                <tbody>
                  {% for session in mySessions %}
                  <tr>
                    <td>{{ session.classDate|date }}</td>
                    <td>{{ session.name|title }}</td>
                    <td>{{ session.startTime|time }}</td>
                    <td>{{ session.endTime|time }}</td>
                    <td>{{ session.location }}</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
   
</div>
{% else %}
    Sorry, there are no sessions in your schedule.<br>
{% endif %}

classrooms/templates/classrooms/unscheduled.html
<!DOCTYPE html>

<html>
<head>
    <title>Unscheduled Students</title>
</head>

<body>

    {% if sessionDetailList %}
    <div style="float: left; width: 100%; padding: 20px;">
        <div style="float: left;margin:5px;width: 45%;">
            <h3>The following students are not registered for one or more sessions.</h3>
        </div>
        <div style="float: right;width: 45%;">
            <div><h3>date:  {% now "SHORT_DATE_FORMAT" %}</h3></div>
        </div>
    </div>
    <div style="float: left; width: 100%;padding: 20px 20px 20px 40px;border-top: 1px solid #000;border-bottom: 1px solid #000">
        <div>Students:</div><br>
           {% for studentDetail in sessionDetailList %}
        <div>{{forloop.counter}}.  {{ studentDetail.student.user.first_name|capfirst }} {{ studentDetail.student.user.last_name|capfirst }}
	{% for session in studentDetail.missingSessions %}
		&nbsp;(start time: {{session}}),&nbsp; 
	{% endfor %}
	</div>
           {% endfor %}
    </div>
    {% else %}
        All students are currently registered for all classes.<br>
    {% endif %}




</body>
</html>